// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qifnprmulqjiibsnwjmi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFpZm5wcm11bHFqaWlic253am1pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMwODE1MjIsImV4cCI6MjA1ODY1NzUyMn0.ncvuzMv4jfyL1fNZqeyGjssh_5Fx4_231qpPnqeno6w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);